services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mariadb
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
    volumes:
      - wordpress:/usr/share/webapps
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "8080:8080"
      # - "443:443"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/usr/share/webapps
    env_file:
        - .env
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb